Issue #500: Serialization of a Map fails if the key uses a custom Serializer
eclipse-ee4j/yasson pull request #501
Opened 2021-07-08 07:40 UTC by rmartinc

Issue: https://github.com/eclipse-ee4j/yasson/issues/500

As commented in  the issue the PR just adds two methods to `MapSerializer` (`serializeKey` and `serializeValue`) that should be called previously to serialize the map keys or values. The method is just used to change the index of the type (key=0 or value=1).

Added a new test inside the `MapToEntriesArraySerializerTest.java`. All the needed classes have been added as inner ones inside the same class. If you prefer to move them to the model package just let me know.

Any improvement will be welcomed. :smiley: 

The idea is preparing another PR for 1.x branch when this one is ready.

Thanks in advance!

2021-08-30 06:54 UTC, rmartinc commented
Hi! Any news about this? Do you see it OK?

2021-08-30 07:56 UTC, Verdent commented
Hi @rmartinc , 
Thank you for pinging me. I had some urgent issues to fix in other project, but I would like dedicate several days this week to take care of Yasson stuff :-)

2021-11-04 13:27 UTC, rmartinc commented
Something new about this PR? We are also interested in this one... Thanks in advance!

2021-11-10 15:20 UTC, Verdent requested changes

2021-11-11 09:11 UTC, rmartinc commented on src/test/java/org/eclipse/yasson/serializers/MapToEntriesArraySerializerTest.java
> +        assertEquals(mapObject, resObject);
Done! I have also read the json string as a JsonObject and checked all the "values" array is as expected. Regards!

2021-11-16 08:57 UTC, Verdent approved these changes

2021-11-16 08:57 UTC, merged