NPE when serializing a Timestamp field with custom date-time formatter
eclipse-ee4j/yasson pull request #577
Opened 2022-09-05 13:30 UTC by greek1979

While working on an unrelated project, I found an issue in Yasson when trying to serialize a POJO with a SQL Timestamp field with a custom date-time formatter enabled in Yasson configuration. The default formatters works just fine, but any explicitly specified formatter produces an NPE in ``SqlTimestampSerializer::formatWithFormatter`` method as it calls ``AbstractDateSerializer::toTemporalAccessor`` method which simply casts its argument to a ``TemporalAccessor``. This does not work with legacy java.sql.Timestamp object, however, as Timestamp does not implement a TemporalAccessor read-only interface.

Here is a small patch to the ``SqlTimestampSerializer`` class to convert a Timestamp into a ``LocalDateTime`` (Java 8 Date API) as both hold the same moment-in-time value, UTC time zone, so no information loss occurs. Resulting temporal field cannot be still serialized to JSON with a custom date-time format that includes unsupported elements such as time zone, for example, as neither SQL ``Timestamp`` nor ``LocaDateTime`` contain any time zone information. This is expected and is by design (of a rather messy ``java.sql.Timestamp`` class).

2022-09-06 11:26 UTC, greek1979 commented
Sorry about a tab character that failed the prebuild checks; replaced it with whitespaces now.

2022-09-06 12:01 UTC, Verdent commented
Hi @greek1979 , thank you for providing this patch :-) May I ask you please to also include test, so we can prevent regression?

2022-09-06 16:31 UTC, greek1979 commented
TL;DR: unit test added.

@Verdent , thank you for pointing this out! Writing a simple test case proved to be an enlightening experience, in fact. As I discovered that an ``Instant`` is not a good substitute for SQL timestamp; it does not expose any DATE fields. A time zone-agnostic ``LocalDateTime`` proved to be a better alternative.

2023-02-17 10:25 UTC, greek1979 commented
Rebased feature branch from master to fix all the copyright errors that Checkstyle complained about yesterday...

2024-09-11 11:57 UTC, greek1979 commented
Updated this old pull request so the copyright year would comply with Checkstyle strict requirements...

2025-03-17 09:01 UTC, greek1979 commented
Updated the copyrights in all three affected source files again to indicate current year, 2025.

2025-12-17 15:25 UTC, greek1979 commented
Any thoughts on this PR? Or otherwise I will soon need to bump up [again] the copyright text to 2026 .. :-)

2025-12-17 17:00 UTC, KyleAure approved these changes

2025-12-17 17:02 UTC, KyleAure commented
This change looks good to me and seems to be very in demand. My review is non-binding (for now 🤞🏼)

2026-03-17 11:41 UTC, greek1979 commented
Any updates on this? (just wondering, every quarter or so since 2022 :-) )

2026-03-17 14:06 UTC, KyleAure requested changes

2026-03-17 14:06 UTC, KyleAure commented on src/main/java/org/eclipse/yasson/internal/serializer/types/SqlTimestampSerializer.java
> +        return LocalDateTime.ofInstant(value.toInstant(), UTC);
```suggestion
        // convert SQL Timestamp into a Instant to unlock TemporalAccessor access
        return toInstant(value);
```
Suggestion: Let's return Instant instead of LocalDateTime to stay consistent with DateSerializer and SqlDateSerializer.  I could see us wanting to refactor this serializer in the future to extend `DateSerializer`.  

Sorry I did not catch this before.

2026-07-23 13:38 UTC, KyleAure commented on src/main/java/org/eclipse/yasson/internal/serializer/types/SqlTimestampSerializer.java
> +import java.time.LocalDateTime;
```suggestion
```

2026-07-27 13:06 UTC, closed without merging