[#583] @JsonbCreator uses PropertyNamingStrategy.
eclipse-ee4j/yasson pull request #584
Opened 2022-12-10 13:25 UTC by bmarwell

This *might* work, but I am not sure about what to pass in `src/main/java16/org/eclipse/yasson/internal/ClassMultiReleaseExtension.java`.

2023-01-06 12:23 UTC, Verdent requested changes

2023-01-06 12:23 UTC, Verdent commented on src/main/java16/org/eclipse/yasson/internal/ClassMultiReleaseExtension.java
> +                return introspector.createJsonbCreator(declaredConstructors[0], null, clazz, pns -> pns);
I might say, add PropertyNamingStrategy parameter. This class is in internal package so it should be fine to change it. That should fix it even for constructors without creator annotation

2023-01-06 12:26 UTC, Verdent commented
Watch out for those copyright failures :-) It should now be 2023.

2023-01-08 15:30 UTC, bmarwell commented
> Watch out for those copyright failures :-) It should be 2023 now.

Actually the plugin does not check commit date, but author date. As I amended the previous commit, it must be 2022 according to the plugin. Unexpected, but that is what it takes to make the plugin happy. :)

2023-01-13 08:18 UTC, Verdent commented
Oh it seems you are having typo there :-)

2023-01-13 19:10 UTC, bmarwell commented
Sorry, broken keyboard (spilled soda over it) 😆

2023-02-13 14:50 UTC, jhanders34 commented
Any more progress on this PR?

2023-02-13 15:11 UTC, Verdent commented
Oh, it seems it is failing on incorrectly separated imports. Otherwise, I think it is OK.

2023-02-13 18:41 UTC, bmarwell commented
> Oh, it seems it is failing on incorrectly separated imports. Otherwise, I think it is OK.

Sigh, sorry! I am too used to checking in IDE config 😞  will fix this ASAP.

2023-02-15 11:52 UTC, Verdent commented
Perfect, thank you for this contribution @bmarwell

2023-02-15 11:52 UTC, Verdent approved these changes

2023-02-15 11:53 UTC, merged